### PR TITLE
Fix ESLint unused parameter issue

### PR DESCRIPTION
**Pull request by michal-simon**
Fixing the ESLint issue with an unused variable. Basically, it needs to have `React` imported because of transpilation. It is covered in detail in this [article ](https://medium.com/@Zwenza/why-do-you-need-to-import-react-in-functional-components-7385e4329ffb).

To have fully working React you need to have `.jsx` files according to their documentation or adjust the ESLint configuration described in [Codeac's documentation](https://www.codeac.io/documentation/eslint-configuration.html#react)

I hope this is helpful.

### CODE REVIEW

**Comment by ondrejsika** [comment]
Thanks @michal-simon!

Is the React import (d17cc92) really necessary?

**Comment by michal-simon** [comment]
Your welcome! :)

According to the React principles it is. Otherwise, there will be no reference to `React` when the HTML is transpired to `React.createElement`. 

Reference: [https://medium.com/@Zwenza/why-do-you-need-to-import-react-in-functional-components-7385e4329ffb](https://medium.com/@Zwenza/why-do-you-need-to-import-react-in-functional-components-7385e4329ffb)

**Comment by ondrejsika** [comment]
Cool, I've learned a bit of React again ;) Thx @michal-simon

**Comment by michal-simon** [comment]
Your welcome. Nice to hear that! Always happy to help. :)

**Pull request merged**
